# Generated by Django 3.0.8 on 2020-07-13 06:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('screenshot', models.ImageField(upload_to='images/')),
                ('project_name', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('details', models.TextField()),
                ('project_url', models.CharField(max_length=50)),
                ('user_project_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design', models.CharField(max_length=30)),
                ('usability', models.CharField(default=0, max_length=8)),
                ('content', models.CharField(max_length=8)),
                ('average', models.FloatField(max_length=8)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rate', to='sites.Project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_picture', models.ImageField(blank=True, upload_to='images/')),
                ('user', models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('bio', models.TextField(default='', max_length=50, null=True)),
                ('contact_info', models.CharField(blank=True, max_length=200)),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
                ('profile_Id', models.IntegerField(default=0)),
                ('rate', models.ManyToManyField(max_length=30, related_name='image', to='sites.Project')),
            ],
            options={
                'db_table': 'profiles',
            },
        ),
    ]
