# Generated by Django 3.0.8 on 2020-07-12 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_auto_20200712_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rate',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='join_date',
            new_name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='all_projects',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_Id',
        ),
        migrations.RemoveField(
            model_name='project',
            name='user_project_id',
        ),
        migrations.AddField(
            model_name='project',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project', to='sites.Profile'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='content',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='creativity',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='rate',
            name='design',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='rate',
            name='usability',
            field=models.CharField(default=0, max_length=8),
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='rate',
            table=None,
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
