# Generated by Django 3.0.8 on 2020-07-12 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0004_auto_20200713_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_Id',
            field=models.IntegerField(default=0),
        ),
    ]
