# Generated by Django 3.0.8 on 2020-07-12 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0005_profile_profile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='profile',
        ),
        migrations.AddField(
            model_name='profile',
            name='all_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='sites.Project'),
        ),
        migrations.AddField(
            model_name='project',
            name='user_project_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterModelTable(
            name='profile',
            table='profiles',
        ),
    ]
