# Generated by Django 3.0.8 on 2020-07-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0006_auto_20200713_0249'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='average',
            field=models.IntegerField(choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0),
        ),
    ]
